# Generated by Django 5.2 on 2025-06-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like_post_likes_scrap_post_scrap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
    ]
