# Generated by Django 5.2 on 2025-05-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_postcategory_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
